#!/usr/bin/env bash

while getopts ":j" opt; do
    case $opt in
    j)
        jobfile=$OPTARG
        ;;
    \?)
        echo "Invalid option: -$OPTARG" >&2
        exit 1
        ;;
    :)
        echo "Option -$OPTARG requires an argument." >&2
        exit 1
        ;;
  esac
done

shift $(($OPTIND-1))
directory_name="$1"

if [[ -d "$directory_name" && $(ls -A "$directory_name") ]]; then
    cd "$directory_name"
elif [[ -z "$directory_name" ]]; then
    echo "Submitting the current directory!"
else
    echo "The directory $directory_name does not exist!"
    exit 1
fi

if [[ -z $jobfile ]]; then
    qsub qsub.parallel
else
    qsub $jobfile
fi
